### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by ChmaraX** [FRINXio/frinx-uniconfig-ui#12]
Unhandled error when opening empty Task list
![Screenshot from 2019-06-29 21-06-59](https://user-images.githubusercontent.com/32128755/60388459-3117a480-9ab2-11e9-821c-3fa70a7b1d35.png)

**Comment by TomasHodor** [comment]
https://github.com/FRINXio/frinx-uniconfig-ui/pull/14
