### ISSUE TITLE
Link_aggregation [DEMO] : incorrectly escaped characters in default values

### ISSUE THREAD

**Issue by ChmaraX** [FRINXio/frinx-uniconfig-ui#13]
Wrong default values in wf: Link_aggregation [DEMO]
![Screenshot from 2019-07-01 12-08-52](https://user-images.githubusercontent.com/32128755/60428406-097f2400-9bf9-11e9-9ef2-e7611e561f3e.png)
`    
"node1_ifaces[Interfaces for node1][[\"GigabitEthernet0/0/0/0\", \"GigabitEthernet0/0/0/1\"]]",
"node2_ifaces[Interfaces for node2][[\"GigabitEthernet0/0/0/1\", \"GigabitEthernet0/0/0/2\", \"GigabitEthernet0/0/0/3\"]]"
`

**Comment by TomasHodor** [comment]
Fixed
