### ISSUE TITLE
snapshot stored but not displayed

### ISSUE THREAD

**Issue by gwieser1234** [FRINXio/frinx-uniconfig-ui#16]
I tried to store a snap shot, but could not load it 
<img width="651" alt="Screen Shot 2019-07-03 at 11 42 11 AM" src="https://user-images.githubusercontent.com/6385994/60581779-cf905800-9d87-11e9-9faf-e7274ad403c5.png">
<img width="550" alt="Screen Shot 2019-07-03 at 11 42 19 AM" src="https://user-images.githubusercontent.com/6385994/60581780-cf905800-9d87-11e9-883d-4806da36602a.png">

**Comment by ChmaraX** [comment]
https://frinxhelpdesk.atlassian.net/browse/FM-153

**Comment by TomasHodor** [comment]
https://github.com/FRINXio/frinx-uniconfig-ui/pull/19
