### ISSUE TITLE
Add fuzzy search in workflows

### ISSUE THREAD

**Issue by moravekl** [FRINXio/frinx-uniconfig-ui#25]
When searching for workflows, it would be nice if it would be possible to look for workflows by just searching for keywords. Currently, if I'm looking for a workflow called "Add_cli_device_to_inventory / 1" for example, I have to use underscores to for results to be returned.

For example I could search for "device add inventory" to look for all workflows that add a device to inventory, be it a cli device or something else.

**Comment by TomasHodor** [comment]
https://github.com/FRINXio/frinx-uniconfig-ui/pull/56/commits/77aedc18ee6f5e795df63569441299e73e8e001f
