### ISSUE TITLE
Exceptions thrown when large graphs are supposed to be rendered

### ISSUE THREAD

**Issue by moravekl** [FRINXio/frinx-uniconfig-ui#26]
Occasionally, if a workflow with multiple sub-workflows is to be rendered and not all data was transferred yet, clicking the "Execution Flow" tab throws an error.

![Screenshot from 2019-07-29 14-46-44](https://user-images.githubusercontent.com/48355717/62049583-d3d95500-b20f-11e9-8fe2-deaa6607d0b9.png)

**Comment by TomasHodor** [comment]
fix: https://github.com/FRINXio/frinx-uniconfig-ui/pull/44/commits/249b6502e6edad89a02b8133b8b0fd238e73ccd5
