### ISSUE TITLE
Add visible labels to workflows

### ISSUE THREAD

**Issue by fontealpina** [FRINXio/frinx-uniconfig-ui#34]
Here: 

![Screenshot from 2019-08-07 08-19-45](https://user-images.githubusercontent.com/10811370/62599326-36a3ae00-b8ec-11e9-82ef-ad6c72f977c9.png)
for each line should be present a list of labels 
otherwise is not clear the difference between label and keyword.
Something similar to this:
![Screenshot from 2019-08-07 08-22-10](https://user-images.githubusercontent.com/10811370/62599437-84201b00-b8ec-11e9-9233-8d1b5417aec7.png)

**Comment by TomasHodor** [comment]
https://github.com/FRINXio/frinx-uniconfig-ui/commit/49b8cbe09f31fb1ce6fb08ea89731ead7eaa7ad0
