### ISSUE TITLE
Browser ask to save password when a device is mounted

### ISSUE THREAD

**Issue by fontealpina** [FRINXio/frinx-uniconfig-ui#37]
The browser should not ask to save the password of a device
When a device is mounted then the browser ask to save the password. 
It should not appear this pop up
![Screenshot from 2019-08-07 11-33-02](https://user-images.githubusercontent.com/10811370/62612204-3fee4400-b907-11e9-8ade-705c9f271737.png)

obs: @ChmaraX

**Comment by TomasHodor** [comment]
https://github.com/FRINXio/frinx-uniconfig-ui/commit/efc28e4eb4c04ce2c025482bdd67295d21ee43b8
