### ISSUE TITLE
add "Comma separated list" in description

### ISSUE THREAD

**Issue by fontealpina** [FRINXio/frinx-uniconfig-ui#38]
In blacklist description should be added 'Comma separated list'
![Screenshot from 2019-08-07 11-44-25](https://user-images.githubusercontent.com/10811370/62613329-8e044700-b909-11e9-859e-19d1d713f049.png)

**Comment by fontealpina** [comment]
@ChmaraX @TomasHodor 
I was thinking that for the blacklist string we could allow two type of syntax:  
aaa,bbb,ccc as it is now
but also 
"aaa","bbb","ccc"
in this way could be possible to copy from json as it is in Postman

**Comment by TomasHodor** [comment]
https://github.com/FRINXio/frinx-uniconfig-ui/commit/e6fea12e78b3b9bc89aefc445a96c99f5e4494e5
