### ISSUE TITLE
pagination in workflow defs creates error

### ISSUE THREAD

**Issue by gwieser1234** [FRINXio/frinx-uniconfig-ui#49]
When I click on "100" in the pagination tab on the lower left under the table I get the following error:
<img width="1140" alt="Screen Shot 2019-09-06 at 4 59 04 PM" src="https://user-images.githubusercontent.com/6385994/64438060-b1b4db80-d0c7-11e9-8a49-1c8d0a51d57a.png">

**Comment by TomasHodor** [comment]
FIX: https://github.com/FRINXio/frinx-uniconfig-ui/pull/50/commits/47e8fed5384712a2ac5b59db7264f329580515ad
